package db

// google fit (all-data folder)
type AutoGenerated struct {
	DataSource string `json:"Data Source"`
	DataPoints []struct {
		FitValue []struct {
			Value struct {
				IntVal int `json:"intVal"`
				FpVal  int `json:"fpVal"`
			} `json:"value"`
		} `json:"fitValue"`
		OriginDataSourceID string `json:"originDataSourceId"`
		EndTimeNanos       int64  `json:"endTimeNanos"`
		DataTypeName       string `json:"dataTypeName"`
		StartTimeNanos     int64  `json:"startTimeNanos"`
		ModifiedTimeMillis int64  `json:"modifiedTimeMillis"`
		RawTimestampNanos  int    `json:"rawTimestampNanos"`
	} `json:"Data Points"`
}
